name: opus_dart
version: 1.0.4
author: EPNW <prokopwieler.hardundsoftware@gmail.com>
homepage: https://github.com/EPNW/opus_dart
description: Wraps libopus in dart, and additionally provides a dart friendly API for encoding and decoding
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  meta: ^1.3.0
  ffi: ^1.0.0