name: opus_dart
version: 1.0.0
author: EPNW <prokopwieler.hardundsoftware@gmail.com>
homepage: https://github.com/EPNW/opus_dart
description: libopus wrappers for dart
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  ffi: ^0.1.3
  meta: ^1.1.8
dev_dependencies:
  ffi_tool:
    git:
      url: git://github.com/dart-interop/ffi_tool.git
      ref: v0.3.0
