name: opus_dart
version: 2.0.1
homepage: https://github.com/EPNW/opus_dart
description: Wraps libopus in dart, and additionally provides a dart friendly API for encoding and decoding
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  ffi: ^1.0.0