name: opus_dart_generation
version: 2.0.0
homepage: https://github.com/EPNW/opus_dart
description: Generates the dart wrappers for opus.
environment:
  sdk: ">=2.12.0 <3.0.0"
dev_dependencies:
  ffi_tool:
    git:
      url: https://github.com/dart-interop/ffi_tool.git
      ref: v0.4.0
